import { FormEvent, useEffect, useState } from 'react';
import './user.css';

type Credit = {user:{email:string};total_credit:string;reserved_credit:string;spent_credit:string;available_credit:string};
type Item = {mandate_id:string;text:string;status:string;decision:string|null;ticket_id:string|null;ticket_hash:string|null;results?:{evidence_id:string;result:unknown}[]};
type CreditEvent = {event_id:string;event_type:string;amount:string;created_at:string};
const messages:Record<string,string>={CREDENTIALS_INVALID:'Revisa tu email y contraseña.',USER_CREDIT_INSUFFICIENT:'No tienes crédito suficiente para esta consulta.',PUBLIC_DAILY_SPEND_CAP_EXCEEDED:'La capacidad de hoy se ha agotado. Inténtalo mañana.',PUBLIC_RATE_LIMITED:'Has alcanzado el límite de consultas. Inténtalo más tarde.',AUTH_RATE_LIMITED:'Demasiados intentos. Espera unos minutos.',PASSWORD_LENGTH_12_TO_128:'Usa una contraseña de entre 12 y 128 caracteres.',EMAIL_INVALID:'Introduce un email válido.',USER_ONBOARDING_UNAVAILABLE:'El registro estará disponible en breve.',REQUEST_QUEUED_RETRY_SAME_KEY:'La consulta está guardada. Puedes reintentar enviarla sin duplicarla.'};
export const creditLabel=(value:string)=>`${Number(value).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:6})} créditos`;
export const stateLabel=(value:string)=>({TICKETED:'Completada',FAILED:'No se pudo completar',RECEIVED:'Recibida',ACQUIRING:'Buscando información',EVALUATING:'Revisando evidencia',DECIDING:'Preparando resultado'}[value]||'En curso');

async function call<T>(path:string,body?:unknown,key?:string):Promise<T>{
  const response=await fetch('/api/v1/users'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined});
  const data=await response.json().catch(()=>({}));
  if(!response.ok){if(response.status===401)throw new Error('SESSION');const code=typeof data.detail==='string'?data.detail:'';throw new Error(messages[code]||'No pudimos completar la solicitud. Inténtalo de nuevo.');}
  return data as T;
}

export function UserApp(){
  const [credit,setCredit]=useState<Credit|null>(null),[ready,setReady]=useState(false),[mode,setMode]=useState<'register'|'login'>('register');
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [query,setQuery]=useState(''),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID()),[items,setItems]=useState<Item[]>([]),[events,setEvents]=useState<CreditEvent[]>([]),[selected,setSelected]=useState<Item|null>(null);
  const [welcome,setWelcome]=useState('0.25');
  async function refresh(){
    try{const [c,h,e]=await Promise.all([call<Credit>('/me/credit'),call<Item[]>('/me/mandates'),call<CreditEvent[]>('/me/credit/events')]);setCredit(c);setItems(h);setEvents(e);}
    catch(e){if((e as Error).message==='SESSION'){setCredit(null);setItems([]);setEvents([]);setSelected(null);}else setError((e as Error).message);}
    finally{setReady(true);}
  }
  useEffect(()=>{void refresh();void call<{welcome_credit:string}>('/status').then(s=>setWelcome(s.welcome_credit)).catch(()=>{});},[]);
  useEffect(()=>{if(!credit)return;const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);},[credit?.user.email]);
  async function authenticate(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await call('/'+mode,{email,password});setPassword('');await refresh();}catch(e){setError((e as Error).message==='SESSION'?'Revisa tu email y contraseña.':(e as Error).message);}finally{setBusy(false);}}
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await call('/me/mandates',{text:query,max_budget_usdc:'0.01'},requestKey);setQuery('');setRequestKey(crypto.randomUUID());await refresh();}catch(e){setError((e as Error).message==='SESSION'?'Tu sesión terminó. Vuelve a entrar.':(e as Error).message);}finally{setBusy(false);}}
  async function logout(){try{await call('/logout',{});setCredit(null);setItems([]);setEvents([]);setSelected(null);setQuery('');setError('');}catch{setError('No pudimos cerrar la sesión. Inténtalo de nuevo.');}}
  async function open(item:Item){try{setSelected(await call<Item>('/me/mandates/'+item.mandate_id));}catch(e){setError((e as Error).message);}}
  return <main className="user-portal"><header className="user-header"><a href="/" aria-label="Inicio PRAMA-Dynamagh">PRAMA<span>—</span>Dynamagh</a>{credit&&<button onClick={()=>void logout()}>Cerrar sesión</button>}</header>
    {!ready?<p role="status">Cargando tu espacio…</p>:!credit?<section className="user-entry"><div><p className="user-eyebrow">INFORMACIÓN CON EVIDENCIA</p><h1>Haz una consulta.<br/>Conserva la evidencia.</h1><p>Un espacio para tus preguntas, sus resultados y un registro verificable de cada consulta.</p><div className="user-welcome"><strong>{creditLabel(welcome)}</strong><span>de bienvenida al crear tu cuenta.</span></div></div><form className="user-card" onSubmit={authenticate}><h2>{mode==='register'?'Crea tu cuenta':'Bienvenido de nuevo'}</h2><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254}/></label><label>Contraseña<input type="password" autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={12} maxLength={128}/></label><small>Entre 12 y 128 caracteres. Guarda tu contraseña: la recuperación no está disponible todavía.</small>{error&&<p className="user-error" role="alert">{error}</p>}<button className="user-primary" disabled={busy}>{busy?'Un momento…':mode==='register'?'Crear cuenta y empezar':'Entrar'}</button><button type="button" onClick={()=>{setMode(mode==='register'?'login':'register');setError('');}}>{mode==='register'?'Ya tengo cuenta':'Crear una cuenta'}</button></form></section>:<>
      <section className="user-account"><div><p className="user-eyebrow">TU ESPACIO</p><h1>¿Qué quieres consultar?</h1><p>{credit.user.email}</p></div><div className="user-balance"><span>Disponible</span><strong>{creditLabel(credit.available_credit)}</strong><small>{creditLabel(credit.reserved_credit)} en consultas pendientes</small></div></section>
      {error&&<p className="user-error" role="alert">{error}</p>}<form className="user-card user-query" onSubmit={submit}><label htmlFor="user-query">Tu consulta</label><textarea id="user-query" placeholder="Escribe una pregunta concreta…" required maxLength={20000} value={query} onChange={e=>{setQuery(e.target.value);setRequestKey(crypto.randomUUID());}}/><div><p>Máximo 0.01 créditos por consulta. El sobrante se devuelve a tu saldo.</p><button className="user-primary" disabled={busy||!query.trim()||Number(credit.available_credit)<0.01}>{busy?'Enviando…':'Consultar'}</button></div></form>
      <div className="user-columns"><section className="user-card"><h2>Tus consultas</h2>{!items.length?<p>Aquí aparecerán tus consultas y sus resultados.</p>:<ul className="user-history">{items.map(item=><li key={item.mandate_id}><button onClick={()=>void open(item)}><span>{item.text}</span><small>{stateLabel(item.status)}</small></button></li>)}</ul>}</section><section className="user-card"><h2>Movimientos de crédito</h2><p>Usado: {creditLabel(credit.spent_credit)}</p><ul className="user-events">{events.map(e=><li key={e.event_id}><span>{{WELCOME_CREDIT:'Bienvenida',SPEND_RESERVATION:'Reserva de consulta',SPEND_SETTLEMENT:'Consulta realizada',RESERVATION_RELEASE:'Crédito liberado'}[e.event_type]||'Movimiento'}</span><strong>{creditLabel(e.amount)}</strong></li>)}</ul></section></div>
      {selected&&<section className="user-card user-result"><button onClick={()=>setSelected(null)} aria-label="Cerrar resultado">Cerrar</button><h2>{selected.text}</h2><p>{stateLabel(selected.status)}</p>{selected.results?.map(r=><pre key={r.evidence_id}>{typeof r.result==='string'?r.result:JSON.stringify(r.result,null,2)}</pre>)}{selected.ticket_hash&&<><p>Identificador verificable del resultado</p><code>{selected.ticket_hash}</code></>}</section>}
    </>}<footer className="user-footer">PRAMA-Dynamagh · Cada consulta conserva su propio registro.</footer></main>;
}
